// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzrqfcnbynxphgmguoor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cnFmY25ieW54cGhnbWd1b29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODkzMjMsImV4cCI6MjA2NTY2NTMyM30.B1oud2rKOF05GqbFEYxpJhc6Xc1wv9rRdmoXi11CwAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});